TICKER_TO_NAME = {
    "RELIANCE": "Reliance Industries",
    "HDFCBANK": "HDFC Bank",
    "ICICIBANK": "ICICI Bank",
    "INFY": "Infosys",
    "TCS": "Tata Consultancy Services",
    "BHARTIARTL": "Bharti Airtel",
    "SBIN": "State Bank of India",
    "BAJFINANCE": "Bajaj Finance",
    "AXISBANK": "Axis Bank",
    "KOTAKBANK": "Kotak Mahindra Bank",
    "LT": "Larsen Toubro",
    "HINDUNILVR": "Hindustan Unilever",
    "SUNPHARMA": "Sun Pharmaceutical Industries",
    "ADANIENT": "Adani Enterprises",
    "ADANIPORTS": "Adani Ports",
    "BAJAJ-AUTO": "Bajaj Auto",
    "BAJAJFINSV": "Bajaj Finserv",
    "MARUTI": "Maruti Suzuki",
    "NTPC": "NTPC",
    "TATASTEEL": "Tata Steel",
    "ONGC": "Oil Natural Gas Corporation",
    "COALINDIA": "Coal India",
    "ITC": "ITC Limited",
    "HCLTECH": "HCL Technologies",
    "WIPRO": "Wipro",
    "TECHM": "Tech Mahindra",
    "INDIGO": "IndiGo InterGlobe Aviation",
    "TITAN": "Titan Company",
    "ULTRACEMCO": "UltraTech Cement",
    "NESTLEIND": "Nestle India",
    "APOLLOHOSP": "Apollo Hospitals",
    "DRREDDY": "Dr Reddys Laboratories",
    "CIPLA": "Cipla",
    "JSWSTEEL": "JSW Steel",
    "HINDALCO": "Hindalco Industries",
    "GRASIM": "Grasim Industries",
    "ASIANPAINT": "Asian Paints",
    "TRENT": "Trent Limited",
    "TATACONSUM": "Tata Consumer Products",
    "EICHERMOT": "Eicher Motors",
    "POWERGRID": "Power Grid Corporation India",
    "BEL": "Bharat Electronics",
    "SHRIRAMFIN": "Shriram Finance",
    "SBILIFE": "SBI Life Insurance",
    "HDFCLIFE": "HDFC Life Insurance",
    "JIOFIN": "Jio Financial Services",
    "MAXHEALTH": "Max Healthcare",
    "M&M": "Mahindra Mahindra",
    "TMPV": "Tata Motors",
    "ETERNAL": "Eternal Limited Zomato"
}